# Generated by Django 3.2.12 on 2023-11-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='department',
            new_name='Student',
        ),
    ]
